// Mocks generated by Mockito 5.0.16 from annotations
// in ditonton_apps/test/presentation/provider/tv_show_detail_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as i5;

import 'package:dartz/dartz.dart' as i3;
import 'package:core/common/failure.dart' as i6;
import 'package:core/domain/entities/tv_show.dart' as i9;
import 'package:core/domain/entities/tv_show_detail.dart' as i7;
import 'package:core/domain/repositories/tv_show_repository.dart' as i2;
import 'package:core/domain/usecases/tv_show/get_tv_show_detail.dart'
    as i4;
import 'package:core/domain/usecases/tv_show/get_tv_show_recommendations.dart'
    as i8;
import 'package:core/domain/usecases/tv_show/get_watchlist_status_tv_show.dart'
    as i10;
import 'package:core/domain/usecases/tv_show/remove_watchlist.dart' as i12;
import 'package:core/domain/usecases/tv_show/save_watchlist.dart' as i11;
import 'package:mockito/mockito.dart' as i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTVShowRepository_0 extends i1.Fake implements i2.TvRepository {
}

class _FakeEither_1<L, R> extends i1.Fake implements i3.Either<L, R> {}

/// A class which mocks [GetTVShowDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVShowDetail extends i1.Mock implements i4.GetTvDetail {
  MockGetTVShowDetail() {
    i1.throwOnMissingStub(this);
  }

  @override
  i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as i2.TvRepository);
  @override
  i5.Future<i3.Either<i6.Failure, i7.TvShowDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<i3.Either<i6.Failure, i7.TvShowDetail>>.value(
              _FakeEither_1<i6.Failure, i7.TvShowDetail>())) as i5
          .Future<i3.Either<i6.Failure, i7.TvShowDetail>>);
}

/// A class which mocks [GetTVShowRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVShowRecommendations extends i1.Mock
    implements i8.GetTvRecommendations {
  MockGetTVShowRecommendations() {
    i1.throwOnMissingStub(this);
  }

  @override
  i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as i2.TvRepository);
  @override
  i5.Future<i3.Either<i6.Failure, List<i9.TvShow>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<i3.Either<i6.Failure, List<i9.TvShow>>>.value(
              _FakeEither_1<i6.Failure, List<i9.TvShow>>())) as i5
          .Future<i3.Either<i6.Failure, List<i9.TvShow>>>);
}

/// A class which mocks [GetWatchListStatusTVShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusTVShow extends i1.Mock
    implements i10.GetWatchListStatusTv {
  MockGetWatchListStatusTVShow() {
    i1.throwOnMissingStub(this);
  }

  @override
  i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as i2.TvRepository);
  @override
  i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as i5.Future<bool>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends i1.Mock implements i11.SaveWatchlist {
  MockSaveWatchlist() {
    i1.throwOnMissingStub(this);
  }

  @override
  i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as i2.TvRepository);
  @override
  i5.Future<i3.Either<i6.Failure, String>> execute(
          i7.TvShowDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<i3.Either<i6.Failure, String>>.value(
                  _FakeEither_1<i6.Failure, String>()))
          as i5.Future<i3.Either<i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends i1.Mock implements i12.RemoveWatchlist {
  MockRemoveWatchlist() {
    i1.throwOnMissingStub(this);
  }

  @override
  i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as i2.TvRepository);
  @override
  i5.Future<i3.Either<i6.Failure, String>> execute(
          i7.TvShowDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<i3.Either<i6.Failure, String>>.value(
                  _FakeEither_1<i6.Failure, String>()))
          as i5.Future<i3.Either<i6.Failure, String>>);
}
