// Mocks generated by Mockito 5.0.16 from annotations
// in ditonton_apps/test/presentation/pages/popular_movies_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as i6;
import 'dart:ui' as i7;

import 'package:core/common/state_enum.dart' as i4;
import 'package:core/domain/entities/movie.dart' as i5;
import 'package:core/domain/usecases/movie/get_popular_movies.dart' as i2;
import 'package:core/presentation/provider/popular_movies_notifier.dart'
    as i3;
import 'package:mockito/mockito.dart' as i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetPopularMovies_0 extends i1.Fake implements i2.GetPopularMovies {
}

/// A class which mocks [PopularMoviesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularMoviesNotifier extends i1.Mock
    implements i3.PopularMoviesNotifier {
  MockPopularMoviesNotifier() {
    i1.throwOnMissingStub(this);
  }

  @override
  i2.GetPopularMovies get getPopularMovies =>
      (super.noSuchMethod(Invocation.getter(#getPopularMovies),
          returnValue: _FakeGetPopularMovies_0()) as i2.GetPopularMovies);
  @override
  i4.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: i4.RequestState.empty) as i4.RequestState);
  @override
  List<i5.Movie> get movies => (super.noSuchMethod(Invocation.getter(#movies),
      returnValue: <i5.Movie>[]) as List<i5.Movie>);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  i6.Future<void> fetchPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#fetchPopularMovies, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as i6.Future<void>);
  @override
  void addListener(i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
